theme: jekyll-theme-cayman
title: Odin Recipes
description: This project is to put all of the HTML knowledge I have been acquiring so far into practice. In this project, I am going to build a basic recipe website.
